// <auto-generated />
namespace _2020_02_15Hello.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class first : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first));
        
        string IMigrationMetadata.Id
        {
            get { return "202002151333548_first"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
